name: Metrics (overview)

on:
  schedule: [{ cron: "0 0 1,11,21 * *" }]
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Classic (followers + stars + repos)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.classic.svg
          base: header, community, repositories
          plugin_stars: yes

      - name: Repositories (focused + a bit random)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.repositories.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: Daokexun.github.io,my-links,Daokexun
          plugin_repositories_order: featured, pinned, random
          plugin_repositories_affiliations: owner
